# action.yml
name: 'Build OpenWRT IPK'
description: 'Builds an OpenWRT package'
branding:
  color: purple
  icon: upload
inputs:
  packageName:
    description: 'The name of the OpenWRT package to build'
    required: true
  makeFilePath:
    description: 'The full filePath of the makeFile to use'
    required: true
  model:
    description: 'The device model (e.g., gl-mt3000, gl-ar300m)'
    required: true
    default: 'gl-mt3000'
outputs:
  package_path:
    description: 'Path to the built package'
    value: ${{ steps.build_firmware.outputs.package_path }}
runs:
  using: "composite"
  steps:
  - name: Setup python 3.12
    uses: actions/setup-python@v4
    with:
      python-version: "3.12"

  - name: Install dependencies
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y jq git libncurses5-dev libncursesw5-dev pigz binutils-dev

  - name: Install Go
    shell: bash
    run: |
      if [ ! -x "/usr/local/go/bin/go" ]; then
        echo "Installing Go..."
        wget https://go.dev/dl/go1.23.4.linux-amd64.tar.gz
        sudo rm -rf /usr/local/go
        sudo tar -I pigz -C /usr/local -xf go1.23.4.linux-amd64.tar.gz
        export PATH=$PATH:/usr/local/go/bin
        echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
        rm go1.23.4.linux-amd64.tar.gz
      fi

  - name: Install python dependancies and run tests
    uses: nick-fields/retry@v2
    with:
      timeout_minutes: 10
      max_attempts: 3
      command: |
        pip3 install setuptools

  - name: Download and extract SDK
    uses: nick-fields/retry@v2
    env:
      MODEL: ${{ inputs.model }}
    with:
      timeout_minutes: 6
      max_attempts: 3
      command: |
        VERSION=23.05.3

        # Determine PLATFORM and SUBTARGET based on MODEL
        case "${{ env.MODEL }}" in
          "gl-mt300n-v2")
            PLATFORM="ramips"
            SUBTARGET="mt76x8"
            ;;
          "gl-ar300m")
            PLATFORM="ath79"
            SUBTARGET="generic"
            ;;
          "gl-mt3000"|"gl-mt6000")
            PLATFORM="mediatek"
            SUBTARGET="filogic"
            ;;
          "gl-e750")
            VERSION="snapshot"
            PLATFORM="ath79"
            SUBTARGET="nand"
            ;;
          "archer_mr200")
            PLATFORM="ramips"
            SUBTARGET="mt7620"
            ;;
          *)
            echo "Unsupported model: ${{ env.MODEL }}"
            exit 1
            ;;
        esac
        echo "PLATFORM=$PLATFORM" >> $GITHUB_ENV
        echo "SUBTARGET=$SUBTARGET" >> $GITHUB_ENV
        SDKDIR=/tmp/openwrt-sdk
        SDK_ARCHIVE="openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
        DOWNLOAD_URL="https://downloads.openwrt.org/releases/${VERSION}/targets/${PLATFORM}/${SUBTARGET}/${SDK_ARCHIVE}"
        SDK_PATH="${SDKDIR}/openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64"
        echo "SDK_PATH=$SDK_PATH" >> $GITHUB_ENV
        if [ ! -d "${SDKDIR}" ] ; then
          mkdir -p "${SDKDIR}"
        fi
        if [ ! -f "${SDKDIR}/${SDK_ARCHIVE}" ]; then
          echo "Downloading SDK..."
          (cd "${SDKDIR}" && curl -O "${DOWNLOAD_URL}")
        fi
        echo "Extracting SDK..."
        tar -I "xz -T0" -xf "${SDKDIR}/${SDK_ARCHIVE}" -C "${SDKDIR}"
        
        # Create necessary SDK directories
        mkdir -p "${SDK_PATH}/include"
        mkdir -p "${SDK_PATH}/bin/packages/$PLATFORM"
        
        # Set GOOS and GOARCH based on the PLATFORM variable
        case "$PLATFORM" in
          "ramips")
            export GOOS="linux"
            export GOARCH="mips"
            if [ "$SUBTARGET" = "mt7620" ]; then
              export GOARM=""
              export GOMIPS="mips32"
              export GO386=""
            else
              export GOARM=""
              export GOMIPS="mips32"
              export GO386=""
            fi
            ;;
          "ath79")
            export GOOS="linux"
            export GOARCH="mips"
            export GOARM=""
            export GOMIPS="mips32"
            export GO386=""
            ;;
          "mediatek")
            export GOOS="linux"
            export GOARCH="arm64"
            export GOARM="arm64"
            export GOMIPS=""
            export GO386=""
            ;;
          *)
            echo "Unsupported platform for GOOS/GOARCH setting."
            exit 1
            ;;
        esac

        # Install opkg-make-index utility for proper package creation
        if [ ! -f "${SDK_PATH}/staging_dir/host/bin/opkg-make-index" ]; then
          echo "Installing opkg-make-index..."
          mkdir -p "${SDK_PATH}/staging_dir/host/bin"
          wget https://raw.githubusercontent.com/shr-project/opkg-utils/master/opkg-make-index -O "${SDK_PATH}/staging_dir/host/bin/opkg-make-index"
          chmod +x "${SDK_PATH}/staging_dir/host/bin/opkg-make-index"
        fi

        echo "Copying ${{github.action_path}}/feeds.conf to "${SDK_PATH}"/feeds.conf"
        cp ${{github.action_path}}/feeds.conf "${SDK_PATH}"/feeds.conf
        cd "${SDK_PATH}"
        ./scripts/feeds update -a
        ./scripts/feeds install -a

  - name: Debug Makefile dump files
    shell: bash
    run: |
      SDK_PATH="${SDKDIR}/openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64"
      
      echo "Examining package dump files..."
      find "${SDK_PATH}/logs/feeds" -name "dump.txt" | while read dumpfile; do
        echo "==== DUMP FILE: $dumpfile ===="
        cat "$dumpfile"
        echo ""
      done

  - name: Build firmware
    id: build_firmware
    env:
      MODEL: ${{ inputs.model }}
      PLATFORM: ${{ env.PLATFORM }}
      SUBTARGET: ${{ env.SUBTARGET }}
      PACKAGE_NAME: ${{ inputs.packageName }}
    uses: nick-fields/retry@v2
    with:
      continue_on_error: 'false'
      timeout_minutes: 18
      max_attempts: 1
      command: |
        VERSION=23.05.3
        MODULE=${{ inputs.packageName }}
        SDKDIR=/tmp/openwrt-sdk
        SDK_PATH="${SDKDIR}/openwrt-sdk-${VERSION}-${PLATFORM}-${SUBTARGET}_gcc-12.3.0_musl.Linux-x86_64"
        
        # Debug information
        echo "Build firmware started"
        echo "Building for model: ${{ inputs.model }}"
        echo "Platform: ${{ env.PLATFORM }}"
        echo "Subtarget: ${{ env.SUBTARGET }}"
        echo "Package name: ${{ inputs.packageName }}"

        # Set up GO environment correctly
        export GOROOT=/usr/local/go
        export PATH=$PATH:$GOROOT/bin

        # 1. Set up correct package directory structure
        echo "Setting up golang and required include files..."

        # 2. Copy makefiles and custom golang packages
        mkdir -p "${SDK_PATH}/package/lang/golang"
        cp -r "${{ github.action_path }}/lang/golang/golang"/* "${SDK_PATH}/package/lang/golang/"
        mkdir -p "${SDK_PATH}/package/lang/golang/files"
        cp -r "${{ github.action_path }}/lang/golang/golang/files"/* "${SDK_PATH}/package/lang/golang/files/" || true

        # 3. Copy golang makefiles
        cp "${{ github.action_path }}/lang/golang/golang-build.sh" "${SDK_PATH}/package/lang/"
        cp "${{ github.action_path }}/lang/golang/golang-compiler.mk" "${SDK_PATH}/package/lang/"
        cp "${{ github.action_path }}/lang/golang/golang-package.mk" "${SDK_PATH}/package/lang/"
        cp "${{ github.action_path }}/lang/golang/golang-values.mk" "${SDK_PATH}/package/lang/"
        cp "${{ github.action_path }}/lang/golang/golang-host-build.mk" "${SDK_PATH}/package/lang/"

        # Copy golang.mk to include directory
        cp ${{github.action_path}}/golang.mk $SDK_PATH/include/golang.mk

        # 4. Go to SDK directory
        cd "${SDK_PATH}"

        # 5. Update and install feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a

        # 6. Ensure golang is installed
        ./scripts/feeds uninstall golang || true
        ./scripts/feeds install -p custom lang/golang
      
        # 7. Configure the build system and enable golang package
        make defconfig
        echo "CONFIG_PACKAGE_golang=y" >> .config

        # Debug information
        echo "Finished `make defconfig`"
        echo "=== SDK Structure ==="
        ls -la "${SDK_PATH}"
        echo "=== Package Directory ==="
        ls -la "${SDK_PATH}/package/lang/golang" || echo "Golang package directory not found"
        echo "=== Feeds Configuration ==="
        cat "${SDK_PATH}/feeds.conf"

        echo "=== Installed Packages ==="
        ./scripts/feeds list -r | grep golang

        # Try to display the package Makefile
        echo "=== Golang Makefile ==="
        cat "${SDK_PATH}/package/lang/golang/Makefile" || echo "Makefile not found"

        # Try compiling with full path
        echo "Compiling golang..."
        make package/lang/golang/compile V=sc || echo "Failed to compile golang"

        # Use find to locate any golang-related files in the build system
        echo "=== Finding golang in build system ==="
        find "${SDK_PATH}" -name golang -type d
        find "${SDK_PATH}" -name "golang*.mk"

        echo "cat .config | grep golang"
        cat .config | grep "golang"

        # Check for any build logs
        echo "=== Build Logs ==="
        find "${SDK_PATH}/logs" -name "*.log" -exec ls -la {} \; || echo "No log files found"

        # Check for any built packages
        echo "=== Output Packages ==="
        find "${SDK_PATH}" -name "*.ipk" || echo "No golang packages found"

        # Make sure include directory exists and copy golang.mk
        mkdir -p $SDK_PATH/include

        cp ${{github.action_path}}/golang.mk $SDK_PATH/include/golang.mk
        # make package/feeds/custom/${{ inputs.packageName }}/compile V=sc

        # 8. Parse feed name from module name
        FEED_NAME=$(echo "$MODULE" | sed -E 's/tollgate-module-(.+)-go/\1/')
        echo "Using feed name: $FEED_NAME for module: $MODULE"

        # 9. Update and install the module feed
        ./scripts/feeds update $FEED_NAME
        ./scripts/feeds install -a -p $FEED_NAME

        # Check if the module is available
        ./scripts/feeds list -r | grep $MODULE

        # 10. Enable the module in the config
        echo "CONFIG_PACKAGE_$MODULE=y" >> .config

        # Debug the package structure
        echo "Debugging package structure:"
        echo "Contents of feed directory:"
        ls -la "${SDK_PATH}/feeds/$FEED_NAME/package/$MODULE" || echo "Feed directory doesn't exist"

        echo "Contents of build directory:"
        BUILD_DIR_PATTERN="${SDK_PATH}/build_dir/target-aarch64_cortex-a53_musl/$MODULE-*"
        ls -la $BUILD_DIR_PATTERN || echo "Build directory doesn't exist"

        echo "Checking Makefile content:"
        cat "${SDK_PATH}/feeds/$FEED_NAME/package/$MODULE/Makefile" || echo "Makefile not found"

        # Find the build directory and pin the problematic package version
        BUILD_DIR_PREFIX="${SDK_PATH}/build_dir/target-aarch64_cortex-a53_musl"
        PACKAGE_BUILD_DIR=$(find "${BUILD_DIR_PREFIX}" -maxdepth 1 -name "$MODULE-*" -type d | head -n 1)
        if [ -n "$PACKAGE_BUILD_DIR" ]; then
          echo "Package build directory: $PACKAGE_BUILD_DIR"
          echo "Pinning bytedance/sonic package version to fix compilation issues..."
          cd "$PACKAGE_BUILD_DIR" && \
          go mod edit -replace github.com/bytedance/sonic=github.com/bytedance/sonic@1.12.10 && \
          go mod edit -require github.com/bytedance/sonic@1.12.10 && \
          go mod tidy && \
          # Verify the pinning worked
          go list -m github.com/bytedance/sonic && \
          # Create vendor directory
          go mod vendor && \
          echo "Checking if sonic is properly vendored:"
          find vendor -path "*/bytedance/sonic*" || echo "Failed to vendor sonic package"
          echo "go.mod after pinning:"
          cat "$PACKAGE_BUILD_DIR/go.mod"
        fi

        echo "Checking if src directory exists:"
        ls -la "${SDK_PATH}/feeds/$FEED_NAME/package/$MODULE/src" || echo "src directory doesn't exist"

        # Add these to your debug step
        echo "Complete file listing in build directory:"
        find "${PKG_BUILD_DIR}" -type f -name "*.go" | sort || echo "No Go files found"

        echo "Go environment:"
        go env || echo "Go not available"

        echo "go.mod contents:"
        cat "${PKG_BUILD_DIR}/go.mod" || echo "go.mod not found"

        # Extract binary name from the module name (replace "tollgate-module-" with "tollgate-")
        BINARY_NAME=$(echo "$MODULE" | sed 's/tollgate-module-/tollgate-/')

        # Try to compile with the feed path
        make package/feeds/$FEED_NAME/$MODULE/compile V=sc

        echo "NOTE: Error messages about '.go_work/build/src/...' not being found are expected and can be ignored"
        echo "      These occur because we're using a custom build process that bypasses OpenWrt's default Go workspace."

        # Find the built binary in the build directory
        BUILD_DIR_PREFIX="${SDK_PATH}/build_dir/target-aarch64_cortex-a53_musl"
        echo "Searching for the built binary ($BINARY_NAME):"
        find "${BUILD_DIR_PREFIX}" -name "$BINARY_NAME" -type f -executable | sort

        # Get the specific build directory for this package
        PACKAGE_BUILD_DIR=$(find "${BUILD_DIR_PREFIX}" -maxdepth 1 -name "$MODULE-*" -type d | head -n 1)
        if [ -n "$PACKAGE_BUILD_DIR" ]; then
          echo "Package build directory: $PACKAGE_BUILD_DIR"
          echo "Listing contents of build directory:"
          ls -la "$PACKAGE_BUILD_DIR"

          # Check if binary exists
          if [ -f "$PACKAGE_BUILD_DIR/$BINARY_NAME" ]; then
            echo "Binary found at: $PACKAGE_BUILD_DIR/$BINARY_NAME"
            echo "binary_path=$PACKAGE_BUILD_DIR/$BINARY_NAME" >> $GITHUB_OUTPUT
            echo "BINARY_PATH=$PACKAGE_BUILD_DIR/$BINARY_NAME" >> $GITHUB_ENV
          else
            echo "Binary not found in expected location!"
            # Search recursively through the build directory
            find "$PACKAGE_BUILD_DIR" -name "$BINARY_NAME" -type f -executable
          fi
        else
          echo "Could not find package build directory!"
        fi

        # Also check the .go_work directory which might contain the compiled binary
        GO_WORK_DIR=$(find "${BUILD_DIR_PREFIX}" -path "*/.go_work/build/bin/linux_arm64" -type d | head -n 1)
        if [ -n "$GO_WORK_DIR" ]; then
          echo "Go work binary directory: $GO_WORK_DIR"
          ls -la "$GO_WORK_DIR"
        fi

        # Inspect the IPK file to see where the binary is supposed to be installed
        # echo "Inspecting IPK file contents:"
        # if [ -n "$PACKAGE_FULLPATH" ]; then
        #  mkdir -p /tmp/ipk-inspect
        #  cp "$PACKAGE_FULLPATH" /tmp/ipk-inspect/
        #  cd /tmp/ipk-inspect
        #  ar x $(basename "$PACKAGE_FULLPATH")
        #  tar -xzf data.tar.gz
        #  echo "Binary in IPK package:"
        #  find . -type f -executable
        #  cd -
        #fi

        # If that doesn't work, try a direct path
        # You might need to find out the actual path where it's installed
        find "${SDK_PATH}/feeds" -name "$MODULE" -type d

        # Debug output to see what was built
        echo "Contents of bin/packages directory:"
        find "${SDK_PATH}/bin/packages" -type f -name "*.ipk" | sort

        # 11. Check the module's Makefile
        MAKEFILE_PATH="${SDK_PATH}/feeds/$FEED_NAME/package/$MODULE/Makefile"
        if [ -f "$MAKEFILE_PATH" ]; then
          echo "Found Makefile for $MODULE at $MAKEFILE_PATH"
          echo "Checking Makefile content:"
          cat "$MAKEFILE_PATH"
        else
          echo "ERROR: Makefile not found at $MAKEFILE_PATH"
          echo "Creating Makefile from template..."

          # Create directory if it doesn't exist
          mkdir -p "${SDK_PATH}/feeds/$FEED_NAME/package/$MODULE"
          echo "Makefile not found in $MAKEFILE_PATH"
          exit 1
        fi
        
        # 16. Generate package index
        cd "${SDK_PATH}"
        ARCH_DIR="${SDK_PATH}/bin/packages/${PLATFORM}_${SUBTARGET}"
        mkdir -p "$ARCH_DIR"
        "${SDK_PATH}/staging_dir/host/bin/opkg-make-index" "$ARCH_DIR" > "${ARCH_DIR}/Packages"
        gzip -9c "${ARCH_DIR}/Packages" > "${ARCH_DIR}/Packages.gz"

        ARCH_DIR="${SDK_PATH}/bin/packages/${PLATFORM}_${SUBTARGET}"
        mkdir -p "$ARCH_DIR"
        
        # 17. Find the final package path
        PACKAGE_FULLPATH=$(find "$ARCH_DIR" -name "$MODULE*.ipk" | head -n 1)

        # After package compilation
        PACKAGE_FULLPATH="${SDK_PATH}/bin/packages/${PLATFORM}_${SUBTARGET}/relay/${MODULE}_*.ipk"

        # Wait for file to be written
        for i in {1..5}; do
          [ -f "$PACKAGE_FULLPATH" ] && break
          echo "Waiting for package file... Attempt $i"
          sleep 2
        done

        # Verify existence
        if [ ! -f "$PACKAGE_FULLPATH" ]; then
          echo "ERROR: Package never appeared at $PACKAGE_FULLPATH"
          find "${SDK_PATH}/bin/packages" -name "*.ipk"
          exit 1
        fi

        # Validate IPK structure
        echo "Validating IPK file format..."
        if [ -f "$PACKAGE_FULLPATH" ]; then
          # Validate IPK structure
          echo "Validating IPK file format..."
          if ! ar t "$PACKAGE_FULLPATH" | grep -q "debian-binary"; then
            echo "ERROR: Invalid IPK format! Missing debian-binary"
            exit 1
          fi

          if ! ar t "$PACKAGE_FULLPATH" | grep -q "control.tar.gz"; then
            echo "ERROR: Invalid IPK format! Missing control.tar.gz"
            exit 1
          fi

          if ! ar t "$PACKAGE_FULLPATH" | grep -q "data.tar.gz"; then
            echo "ERROR: Invalid IPK format! Missing data.tar.gz"
            exit 1
          fi

          # Verify binary in IPK
          mkdir -p /tmp/ipk-inspect
          cp "$PACKAGE_FULLPATH" /tmp/ipk-inspect/
          cd /tmp/ipk-inspect
          ar x $(basename "$PACKAGE_FULLPATH")
          tar -tzf data.tar.gz | grep 'usr/bin/tollgate-relay' || {
            echo "ERROR: Binary missing from package!"
            exit 1
          }

          echo "IPK validation successful!"
          echo "package_path=$PACKAGE_FULLPATH" >> $GITHUB_OUTPUT
          echo "PACKAGE_FULLPATH=$PACKAGE_FULLPATH" >> $GITHUB_ENV
        else
          echo "ERROR: Package file not found at $PACKAGE_FULLPATH"
          exit 1
        fi

