# .github/workflows/build-firmware.yml
name: Build Firmware

on:
  workflow_run:
    workflows: ["Prebuild Golang"]
    types:
      - completed
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    needs: [prebuild-golang]
    # Only run if the triggering prebuild workflow succeeded or if this was triggered directly
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [
          "tollgate-module-relay-go"#,
          #"tollgate-module-merchant-go",
          #"tollgate-module-valve-go",
          #"tollgate-module-whoami-go",
          #"tollgate-module-janitor-go",
          #"tollgate-module-crowsnest-go"
        ]
        target: [
          {model: "gl-ar300m"},
          {model: "gl-mt3000"},
          {model: "gl-mt6000"}
        ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Prebuilt Golang
        uses: actions/download-artifact@v4
        with:
          name: golang-${{ matrix.target.model }}-${{ matrix.target.platform }}-${{ matrix.target.subtarget }}
          path: prebuilt/

      - name: Build OpenWRT Package
        uses: ./ # Uses the local action
        id: build
        with:
          packageName: ${{ matrix.module }}
          makeFilePath: ${{ github.workspace }}/Makefile
          model: ${{ matrix.target.model }}
          platform: ${{ matrix.target.platform }}
          subtarget: ${{ matrix.target.subtarget }}
          prebuilt_golang: prebuilt/golang*.ipk
          golang_hash: ${{ needs.prebuild-golang.outputs.golang_hash }}

      - name: Debug Package Path
        run: |
          echo "Package Path: ${{ steps.build.outputs.package_path }}"
          ls -l 
          ls -l "${{ steps.build.outputs.package_path }}"

      - name: Upload Package to Blossom
        id: upload_package
        uses: c03rad0r/upload-blossom-action@pr/using-nsec-argument-correct-state
        with:
          host: "https://blossom.swissdash.site"
          filePath: ${{ steps.build.outputs.package_path }}
          nostrPrivateKey: ${{ secrets.NSEC }}
