# .github/workflows/build-firmware.yml
name: Build Firmware

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [
          "tollgate-module-relay-go",
          "tollgate-module-merchant-go",
          "tollgate-module-valve-go",
          "tollgate-module-whoami-go",
          "tollgate-module-updater-go",
          "tollgate-module-crowsnest-go"
        ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build OpenWRT Package
        uses: ./ # Uses the local action
        id: build
        with:
          packageName: ${{ matrix.module }}
          makeFilePath: ${{ github.workspace }}/Makefile

      - name: Upload Package to Blossom
        id: upload_package
        uses: c03rad0r/upload-blossom-action@pr/using-nsec-argument-correct-state
        with:
          host: "https://blossom.swissdash.site"
          filePath: ${{ steps.build.outputs.package_path }}
          nostrPrivateKey: ${{ secrets.NSEC }}
