name: Build Firmware

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [
          "tollgate-module-relay-go",
          "merchant",
          "valve",
          "whoami",
          "crowsnest"
        ]
      fail-fast: false  # Added this line to allow other matrix jobs to continue if one fails

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          chmod +x ./build-firmware # Make the script executable

      - name: Build firmware
        run: sudo ./build-firmware gl-mt3000 ${{ matrix.module }}
        # with:
        #  retries: 2
