name: Build Firmware

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [
          "tollgate-module-relay-go",
          "tollgate-module-merchant-go",
          "tollgate-module-valve-go",
          "tollgate-module-whoami-go",
          "tollgate-module-updater-go",
          "tollgate-module-crowsnest-go"
        ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build OpenWRT Package
        uses: ./ # Uses the local action
        with:
          packageName: ${{ matrix.module }}
          makeFilePath: ${{ github.workspace }}/Makefile # Adjust path as needed
