name: Test Release JSON Update

on:
  push:
    branches:
      - update-release-json
  workflow_dispatch:
    inputs:
      modules:
        description: 'Comma-separated list of modules to include'
        required: false
        default: 'relay,valve,whoami'
      models:
        description: 'Comma-separated list of models to include'
        required: false
        default: 'gl-ar300m,gl-mt3000,gl-mt6000'

jobs:
  generate-real-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          path: sdk

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Create Test Package
        run: |
          CURRENT_TIME=$(date +%s)
          echo "This is a test package created at ${CURRENT_TIME}" > test-package-${CURRENT_TIME}.ipk
          echo "PACKAGE_FULLPATH=$(pwd)/test-package-${CURRENT_TIME}.ipk" >> $GITHUB_ENV

      - name: Upload Test Package to Blossom
        id: upload_test
        uses: c03rad0r/cli-blossom-uploader-go@main
        with:
          host: "https://blossom.swissdash.site"
          filePath: ${{ env.PACKAGE_FULLPATH }}
          nostrPrivateKey: ${{ secrets.NSECBECH }}

      - name: Generate NIP-94 Event
        id: generate_event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python@main
        with:
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/
          url: ${{ steps.upload_test.outputs.url }}
          mimeType: application/octet-stream
          fileHash: ${{ steps.upload_test.outputs.hash }}
          content: "Test Module Package"
          nsec: ${{ secrets.NSEC }}
          size: $(stat -c%s "${{ env.PACKAGE_FULLPATH }}")
          architecture: "aarch64_cortex-a53"
          model: "gl-mt3000"
          module: "test-module"
          version: "0.0.1"

      - name: Verify NIP-94 Event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python/verify@main
        with:
          eventId: ${{ steps.generate_event.outputs.eventId }}
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/

      - name: Install nak
        run: |
          sudo wget https://github.com/fiatjaf/nak/releases/download/v0.12.4/nak-v0.12.4-linux-amd64 -O /usr/local/bin/nak
          sudo chmod +x /usr/local/bin/nak

      - name: Verify Event on Network with nak
        run: |
          PUBKEY="${{ secrets.NIP_94_PUBKEY }}"
          # Use our generated event ID directly
          EVENT_ID="${{ steps.generate_event.outputs.eventId }}"
          GENERATED_HASH="${{ steps.upload_test.outputs.hash }}"
          
          echo "Verifying event ID: '$EVENT_ID'"
          
          # Make sure we have a valid event ID
          if [ -z "$EVENT_ID" ] || [ "$EVENT_ID" = "null" ]; then
            echo "::error::Invalid or missing event ID"
            exit 1
          fi
          
          # Save event details to temp file for more reliable processing
          nak req --id "$EVENT_ID" wss://relay.damus.io > event_response.txt
          
          # Check for errors in the response
          if grep -q "ERROR" event_response.txt; then
            echo "::error::Error retrieving event from relay:"
            cat event_response.txt
            exit 1
          fi
          
          # Extract the actual JSON event data
          cat event_response.txt | grep -v "connecting to" | grep -v "NOTICE" > event_data.json
          
          # Validate we have JSON data
          if ! jq empty event_data.json 2>/dev/null; then
            echo "::error::Invalid JSON response from relay"
            cat event_data.json
            exit 1
          fi
          
          echo "Event data from relay:"
          cat event_data.json | jq .
          
          # Extract the hash from the x tag
          EVENT_HASH=$(jq -r '.tags[] | select(.[0] == "x") | .[1]' event_data.json)
          
          echo "Network event hash: '$EVENT_HASH'"
          echo "Generated hash: '$GENERATED_HASH'"
          
          # Verify the hash matches
          if [ "$EVENT_HASH" != "$GENERATED_HASH" ]; then
            echo "::error::Hash mismatch! Expected $GENERATED_HASH but found $EVENT_HASH"
            exit 1
          fi
          
          echo "✅ Event verification successful!"

      - name: Create Event JSON
        run: |
          echo '{
            "eventId": "${{ steps.generate_event.outputs.eventId }}",
            "hash": "${{ steps.upload_test.outputs.hash }}",
            "url": "${{ steps.upload_test.outputs.url }}",
            "module": "test-module",
            "model": "gl-mt3000",
            "architecture": "aarch64_cortex-a53"
          }' > test-event.json
          echo "EVENT_PATH=$(pwd)/test-event.json" >> $GITHUB_ENV

      # - name: Trigger OS Workflow
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: OpenTollGate/tollgate-os
      #     event-type: update-release-json
      #     client-payload: |
      #       {
      #         "nip94_events": {
      #           "events": [
      #             $(cat ${{ env.EVENT_PATH }})
      #           ]
      #         },
      #         "branch": "develop",
      #         "is_test": true
      #       }