name: Test Release JSON Update

on:
  push:
    branches:
      - update-release-json
  workflow_dispatch:
    inputs:
      modules:
        description: 'Comma-separated list of modules to include'
        required: false
        default: 'relay,valve,whoami'
      models:
        description: 'Comma-separated list of models to include'
        required: false
        default: 'gl-ar300m,gl-mt3000,gl-mt6000'

jobs:
  generate-real-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          path: sdk

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Create Test Package
        run: |
          CURRENT_TIME=$(date +%s)
          echo "This is a test package created at ${CURRENT_TIME}" > test-package-${CURRENT_TIME}.ipk
          echo "PACKAGE_FULLPATH=$(pwd)/test-package-${CURRENT_TIME}.ipk" >> $GITHUB_ENV

      - name: Upload Test Package to Blossom
        id: upload_test
        uses: c03rad0r/cli-blossom-uploader-go@main
        with:
          host: "https://blossom.swissdash.site"
          filePath: ${{ env.PACKAGE_FULLPATH }}
          nostrPrivateKey: ${{ secrets.NSECBECH }}

      - name: Generate NIP-94 Event
        id: generate_event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python@main
        with:
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/
          url: ${{ steps.upload_test.outputs.url }}
          mimeType: application/octet-stream
          fileHash: ${{ steps.upload_test.outputs.hash }}
          content: "Test Module Package"
          nsec: ${{ secrets.NSEC }}
          size: $(stat -c%s "${{ env.PACKAGE_FULLPATH }}")
          architecture: "aarch64_cortex-a53"
          model: "gl-mt3000"
          module: "test-module"
          version: "0.0.1"

      - name: Verify NIP-94 Event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python/verify@main
        with:
          eventId: ${{ steps.generate_event.outputs.eventId }}
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/

      - name: Install noscl
        run: |
          wget https://github.com/fiatjaf/noscl/releases/download/v0.6.0/noscl -O /usr/local/bin/noscl
          chmod +x /usr/local/bin/noscl
          
      - name: Verify Event on Network
        run: |
          # Get the pubkey from GitHub secrets
          PUBKEY="${{ secrets.NIP_94_PUBKEY }}"
          if [ -z "$PUBKEY" ]; then
            echo "::error::NIP_94_PUBKEY secret is not set"
            exit 1
          fi
          
          echo "Fetching latest event for pubkey: $PUBKEY"
          
          # Create a temporary config file for noscl
          mkdir -p ~/.config/noscl
          echo '{"relays":["wss://relay.damus.io","wss://nos.lol","wss://nostr.mom"]}' > ~/.config/noscl/config.json
          
          # Fetch the latest events for this pubkey (kind 1063 is NIP-94)
          echo "Fetching latest events for pubkey: $PUBKEY"
          LATEST_EVENTS=$(noscl query --kinds 1063 --authors "$PUBKEY" --limit 5 2>/dev/null || echo '{"error": "No events found"}')
          
          # Print the events to the command line
          echo "Latest events:"
          echo "$LATEST_EVENTS" | jq . || echo "$LATEST_EVENTS"
          
          # Check if we got any events
          if [[ "$LATEST_EVENTS" == *"error"* ]]; then
            echo "::warning::Could not find any events from this pubkey on the network."
          else
            echo "✅ Successfully fetched latest events from the network!"
            
            # Also verify our specific event is there
            EVENT_ID="${{ steps.generate_event.outputs.eventId }}"
            echo "Checking if our event ID $EVENT_ID is in the results..."
            
            if [[ "$LATEST_EVENTS" == *"$EVENT_ID"* ]]; then
              echo "✅ Our specific event was found in the latest events!"
            else
              echo "::warning::Our specific event was not found in the latest events. It may not have propagated yet."
            fi
          fi

      - name: Create Event JSON
        run: |
          echo '{
            "eventId": "${{ steps.generate_event.outputs.eventId }}",
            "hash": "${{ steps.upload_test.outputs.hash }}",
            "url": "${{ steps.upload_test.outputs.url }}",
            "module": "test-module",
            "model": "gl-mt3000",
            "architecture": "aarch64_cortex-a53"
          }' > test-event.json
          echo "EVENT_PATH=$(pwd)/test-event.json" >> $GITHUB_ENV

      # - name: Trigger OS Workflow
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: OpenTollGate/tollgate-os
      #     event-type: update-release-json
      #     client-payload: |
      #       {
      #         "nip94_events": {
      #           "events": [
      #             $(cat ${{ env.EVENT_PATH }})
      #           ]
      #         },
      #         "branch": "develop",
      #         "is_test": true
      #       }