name: Test Release JSON Update

on:
  push:
    branches:
      - update-release-json
  workflow_dispatch:
    inputs:
      modules:
        description: 'Comma-separated list of modules to include'
        required: false
        default: 'relay,valve,whoami'
      models:
        description: 'Comma-separated list of models to include'
        required: false
        default: 'gl-ar300m,gl-mt3000,gl-mt6000'

jobs:
  generate-real-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          path: sdk

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Create Test Package
        run: |
          CURRENT_TIME=$(date +%s)
          echo "This is a test package created at ${CURRENT_TIME}" > test-package-${CURRENT_TIME}.ipk
          echo "PACKAGE_FULLPATH=$(pwd)/test-package-${CURRENT_TIME}.ipk" >> $GITHUB_ENV

      - name: Upload Test Package to Blossom
        id: upload_test
        uses: c03rad0r/cli-blossom-uploader-go@main
        with:
          host: "https://blossom.swissdash.site"
          filePath: ${{ env.PACKAGE_FULLPATH }}
          nostrPrivateKey: ${{ secrets.NSECBECH }}

      - name: Generate NIP-94 Event
        id: generate_event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python@main
        with:
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/
          url: ${{ steps.upload_test.outputs.url }}
          mimeType: application/octet-stream
          fileHash: ${{ steps.upload_test.outputs.hash }}
          content: "Test Module Package"
          nsec: ${{ secrets.NSEC }}
          size: $(stat -c%s "${{ env.PACKAGE_FULLPATH }}")
          architecture: "aarch64_cortex-a53"
          model: "gl-mt3000"
          module: "test-module"
          version: "0.0.1"

      - name: Verify NIP-94 Event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python/verify@main
        with:
          eventId: ${{ steps.generate_event.outputs.eventId }}
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/

      - name: Install noscl
        run: |
          curl -L https://github.com/fiatjaf/noscl/releases/download/v0.6.2/noscl_0.6.2_linux_amd64.tar.gz -o noscl.tar.gz
          tar -xzf noscl.tar.gz
          chmod +x noscl
          sudo mv noscl /usr/local/bin/
          noscl --version

      - name: Fetch Latest Event from NIP-94 Pubkey
        run: |
          # Get the pubkey from environment variable
          PUBKEY="${{ env.NIP_94_PUBKEY }}"
          if [ -z "$PUBKEY" ]; then
            echo "::error::NIP_94_PUBKEY environment variable is not set"
            exit 1
          fi
          
          echo "Fetching latest event for pubkey: $PUBKEY"
          
          # Fetch the latest event from relays
          LATEST_EVENT=$(noscl fetch --kind 1063 --author "$PUBKEY" --limit 1 --relay wss://relay.damus.io --relay wss://nos.lol --relay wss://nostr.mom)
          echo "LATEST_EVENT=$LATEST_EVENT" >> $GITHUB_ENV
          
          # Extract event ID and hash from the event
          EVENT_ID=$(echo "$LATEST_EVENT" | jq -r '.id')
          EVENT_HASH=$(echo "$LATEST_EVENT" | jq -r '.tags[] | select(.[0] == "hash") | .[1]')
          
          echo "Latest Event ID: $EVENT_ID"
          echo "Latest Event Hash: $EVENT_HASH"
          
          # Compare with our generated event
          GENERATED_EVENT_ID="${{ steps.generate_event.outputs.eventId }}"
          GENERATED_HASH="${{ steps.upload_test.outputs.hash }}"
          
          echo "Generated Event ID: $GENERATED_EVENT_ID"
          echo "Generated Hash: $GENERATED_HASH"
          
          # Verify the event was published correctly
          if [ "$EVENT_ID" != "$GENERATED_EVENT_ID" ]; then
            echo "::warning::Event ID mismatch. This may be normal if multiple events were published recently."
          fi
          
          if [ "$EVENT_HASH" != "$GENERATED_HASH" ]; then
            echo "::error::Hash mismatch! Expected $GENERATED_HASH but found $EVENT_HASH"
            exit 1
          fi
          
          echo "✅ Event verification successful!"

          
      - name: Create Event JSON
        run: |
          echo '{
            "eventId": "${{ steps.generate_event.outputs.eventId }}",
            "hash": "${{ steps.upload_test.outputs.hash }}",
            "url": "${{ steps.upload_test.outputs.url }}",
            "module": "test-module",
            "model": "gl-mt3000",
            "architecture": "aarch64_cortex-a53"
          }' > test-event.json
          echo "EVENT_PATH=$(pwd)/test-event.json" >> $GITHUB_ENV

      # - name: Trigger OS Workflow
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: OpenTollGate/tollgate-os
      #     event-type: update-release-json
      #     client-payload: |
      #       {
      #         "nip94_events": {
      #           "events": [
      #             $(cat ${{ env.EVENT_PATH }})
      #           ]
      #         },
      #         "branch": "develop",
      #         "is_test": true
      #       }