name: Test Release JSON Update

on:
  push:
    branches:
      - update-release-json
  workflow_dispatch:
    inputs:
      modules:
        description: 'Comma-separated list of modules to include'
        required: false
        default: 'relay,valve,whoami'
      models:
        description: 'Comma-separated list of models to include'
        required: false
        default: 'gl-ar300m,gl-mt3000,gl-mt6000'

jobs:
  generate-real-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          path: sdk

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Create Test Package
        run: |
          CURRENT_TIME=$(date +%s)
          echo "This is a test package created at ${CURRENT_TIME}" > test-package-${CURRENT_TIME}.ipk
          echo "PACKAGE_FULLPATH=$(pwd)/test-package-${CURRENT_TIME}.ipk" >> $GITHUB_ENV

      - name: Upload Test Package to Blossom
        id: upload_test
        uses: c03rad0r/cli-blossom-uploader-go@main
        with:
          host: "https://blossom.swissdash.site"
          filePath: ${{ env.PACKAGE_FULLPATH }}
          nostrPrivateKey: ${{ secrets.NSECBECH }}

      - name: Generate NIP-94 Event
        id: generate_event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python@main
        with:
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/
          url: ${{ steps.upload_test.outputs.url }}
          mimeType: application/octet-stream
          fileHash: ${{ steps.upload_test.outputs.hash }}
          content: "Test Module Package"
          nsec: ${{ secrets.NSEC }}
          size: $(stat -c%s "${{ env.PACKAGE_FULLPATH }}")
          architecture: "aarch64_cortex-a53"
          model: "gl-mt3000"
          module: "test-module"
          version: "0.0.1"

      - name: Verify NIP-94 Event
        uses: OpenTollGate/nostr-publish-file-metadata-action/python/verify@main
        with:
          eventId: ${{ steps.generate_event.outputs.eventId }}
          relays: wss://relay.damus.io,wss://nos.lol,wss://nostr.mom/

      - name: Install nak
        run: |
          sudo wget https://github.com/fiatjaf/nak/releases/download/v0.12.4/nak-v0.12.4-linux-amd64 -O /usr/local/bin/nak
          sudo chmod +x /usr/local/bin/nak
          
      - name: Verify Event on Network
        run: |
          PUBKEY="${{ secrets.NIP_94_PUBKEY }}"
          # Use our generated event ID directly
          EVENT_ID="${{ steps.generate_event.outputs.eventId }}"
          GENERATED_HASH="${{ steps.upload_test.outputs.hash }}"
          
          echo "Verifying event ID: $EVENT_ID"
          
          # Query the event directly from relay
          echo "Fetching from relay..."
          EVENT_JSON=$(nak req --id "$EVENT_ID" wss://relay.damus.io 2>/dev/null)
          
          # Check if event was found
          if [ -z "$EVENT_JSON" ]; then
            echo "::error::Event not found on relay"
            exit 1
          fi
          
          echo "Event found on network:"
          echo "$EVENT_JSON" | jq .
          
          # Extract the hash from the x tag
          EVENT_HASH=$(echo "$EVENT_JSON" | jq -r '.tags[] | select(.[0] == "x") | .[1]')
          
          echo "Network event hash: $EVENT_HASH"
          echo "Generated hash: $GENERATED_HASH"
          
          # Verify the hash matches
          if [ "$EVENT_HASH" != "$GENERATED_HASH" ]; then
            echo "::error::Hash mismatch! Expected $GENERATED_HASH but found $EVENT_HASH"
            exit 1
          fi
          
          echo "✅ Event verification successful!"

      - name: Create Event JSON
        run: |
          echo '{
            "eventId": "${{ steps.generate_event.outputs.eventId }}",
            "hash": "${{ steps.upload_test.outputs.hash }}",
            "url": "${{ steps.upload_test.outputs.url }}",
            "module": "test-module",
            "model": "gl-mt3000",
            "architecture": "aarch64_cortex-a53"
          }' > test-event.json
          echo "EVENT_PATH=$(pwd)/test-event.json" >> $GITHUB_ENV

      # - name: Trigger OS Workflow
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     repository: OpenTollGate/tollgate-os
      #     event-type: update-release-json
      #     client-payload: |
      #       {
      #         "nip94_events": {
      #           "events": [
      #             $(cat ${{ env.EVENT_PATH }})
      #           ]
      #         },
      #         "branch": "develop",
      #         "is_test": true
      #       }